# Generated by Django 4.2.8 on 2023-12-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField()),
                ('text', models.TextField()),
                ('sender', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Chat_message',
                'verbose_name_plural': 'Chat_messages',
                'db_table': 'chat_message',
            },
        ),
    ]
