# Generated by Django 4.2.8 on 2023-12-24 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'verbose_name': 'Chat_message', 'verbose_name_plural': 'Chat_messages'},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='command',
            field=models.TextField(default='pwd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='chatmessage',
            table='chat_message',
        ),
    ]
